//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genshin_Lyre_Midi_Tool.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Genshin_Lyre_Midi_Tool.Properties.LanguageResource", typeof(LanguageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Track 的本地化字符串。
        /// </summary>
        internal static string editTrack_Text {
            get {
                return ResourceManager.GetString("editTrack.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Name 的本地化字符串。
        /// </summary>
        internal static string fileNameColumn_Text {
            get {
                return ResourceManager.GetString("fileNameColumn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path 的本地化字符串。
        /// </summary>
        internal static string folderLabel_Text {
            get {
                return ResourceManager.GetString("folderLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading 的本地化字符串。
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Idle 的本地化字符串。
        /// </summary>
        internal static string midiState_Idle {
            get {
                return ResourceManager.GetString("midiState.Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading 的本地化字符串。
        /// </summary>
        internal static string midiState_Loading {
            get {
                return ResourceManager.GetString("midiState.Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paused 的本地化字符串。
        /// </summary>
        internal static string midiState_Paused {
            get {
                return ResourceManager.GetString("midiState.Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Playing 的本地化字符串。
        /// </summary>
        internal static string midiState_Playing {
            get {
                return ResourceManager.GetString("midiState.Playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waiting 的本地化字符串。
        /// </summary>
        internal static string midiState_Waiting {
            get {
                return ResourceManager.GetString("midiState.Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Midi File Selected 的本地化字符串。
        /// </summary>
        internal static string NoFile {
            get {
                return ResourceManager.GetString("NoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No MIDI output devices available, the preview will be disabled. 的本地化字符串。
        /// </summary>
        internal static string NoMidiOutPut {
            get {
                return ResourceManager.GetString("NoMidiOutPut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Midi File 的本地化字符串。
        /// </summary>
        internal static string openMidi_Text {
            get {
                return ResourceManager.GetString("openMidi.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        internal static string OpenMidiButton_Text {
            get {
                return ResourceManager.GetString("OpenMidiButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause 的本地化字符串。
        /// </summary>
        internal static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play 的本地化字符串。
        /// </summary>
        internal static string playButton_Text {
            get {
                return ResourceManager.GetString("playButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preview / Play 的本地化字符串。
        /// </summary>
        internal static string previewAndPlay_Text {
            get {
                return ResourceManager.GetString("previewAndPlay.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        internal static string RefreshMidiListButton_Text {
            get {
                return ResourceManager.GetString("RefreshMidiListButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string SaveMidiButton_Text {
            get {
                return ResourceManager.GetString("SaveMidiButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Folder 的本地化字符串。
        /// </summary>
        internal static string selectFolderButton_Text {
            get {
                return ResourceManager.GetString("selectFolderButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string settingsAndAbout_Text {
            get {
                return ResourceManager.GetString("settingsAndAbout.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        internal static string stopButton_Text {
            get {
                return ResourceManager.GetString("stopButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 --------    Valid Range    -------- 的本地化字符串。
        /// </summary>
        internal static string validRangeLabel_Text {
            get {
                return ResourceManager.GetString("validRangeLabel.Text", resourceCulture);
            }
        }
    }
}
